In [1]:
import numpy as np

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
ciao = np.arange(20)
ciao.shape

(20,)

In [17]:
ciao.ndim

1

In [19]:
ciao.reshape((10,2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [20]:
print(ciao)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [22]:
ciao = ciao.reshape((10,2))

In [23]:
print(ciao)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [24]:
ciao.ndim

2

In [25]:
ciao = ciao + 1

In [26]:
print (ciao)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]


In [43]:
souca = np.arange(10)
souca * souca

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [44]:
souca = souca ** 2
souca = souca.reshape((5,2))
print(souca)

[[ 0  1]
 [ 4  9]
 [16 25]
 [36 49]
 [64 81]]


In [47]:
ciao2 = np.arange(20) #creates array with 20 cells already inizializated
ciao2 = ciao2 + 5
print(ciao2)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [48]:
ciao2 = ciao2.reshape((10,2)) #just reshapes that array as you want
#warning!! it has to be a correct size for the dimension of the array
ciao + ciao2


array([[ 6,  8],
       [10, 12],
       [14, 16],
       [18, 20],
       [22, 24],
       [26, 28],
       [30, 32],
       [34, 36],
       [38, 40],
       [42, 44]])

In [49]:
pupo = np.zeros((5,2)) #inizialize an array of zeros
pupo

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [52]:
np.ones((5,2), dtype = np.int)
#dtype ensure that all the ones are integer type 
#Warning! scikit expects np.float arguments in arrays

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [53]:
np.empty((5,2), dtype = np.float) #empty arrays

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [55]:
print(ciao[0,0]) #first cell
print(ciao[0,:]) #first row
print(ciao[:,0]) #first column
print(ciao[2:4,:]) #rows by 2 to 4
print(ciao[2:4,0]) #rows by 2 to 4 of the first column

1
[1 2]
[ 1  3  5  7  9 11 13 15 17 19]
[[5 6]
 [7 8]]
[5 7]


In [56]:
ciao > 5

array([[False, False],
       [False, False],
       [False,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [57]:
ciao[ciao > 5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [58]:
ciao.sum()

210

In [60]:
ciao.sum(axis=0) #sums column (with axis 1 sum rows)

array([100, 110])

In [61]:
ciao.mean(axis=1) #mean of rows with np float

array([ 1.5,  3.5,  5.5,  7.5,  9.5, 11.5, 13.5, 15.5, 17.5, 19.5])

In [63]:
eto = np.array([np.nan, 0, 1, 2, np.nan])
np.isnan(eto)

array([ True, False, False, False,  True])

In [66]:
eto[~np.isnan(eto)]

array([0., 1., 2.])

In [68]:
eto[np.isnan(eto)]=0
eto

array([0., 0., 1., 2., 0.])